-- Additive marketplace migration. Existing business tables are preserved.
CREATE TABLE IF NOT EXISTS market_preferences (
 user_id BIGINT UNSIGNED PRIMARY KEY, intent VARCHAR(40) NOT NULL DEFAULT 'encontrar_clientes',
 consent_version VARCHAR(40) NULL, consent_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_profiles (
 user_id BIGINT UNSIGNED PRIMARY KEY, name VARCHAR(120) NOT NULL,
 photo MEDIUMTEXT NULL, city VARCHAR(100) NOT NULL DEFAULT '', region VARCHAR(100) NOT NULL DEFAULT '',
 latitude DECIMAL(5,2) NULL, longitude DECIMAL(5,2) NULL, skills JSON NOT NULL,
 services TEXT NOT NULL, experience TEXT NOT NULL, bio TEXT NOT NULL,
 price_from DECIMAL(12,2) NULL, price_to DECIMAL(12,2) NULL, availability VARCHAR(300) NOT NULL DEFAULT '',
 radius_km INT NOT NULL DEFAULT 30, mode VARCHAR(15) NOT NULL DEFAULT 'ambos',
 published TINYINT NOT NULL DEFAULT 0, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_posts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(120) NOT NULL, category VARCHAR(80) NOT NULL, description TEXT NOT NULL,
 city VARCHAR(100) NOT NULL DEFAULT '', region VARCHAR(100) NOT NULL DEFAULT '',
 latitude DECIMAL(5,2) NULL, longitude DECIMAL(5,2) NULL, mode VARCHAR(15) NOT NULL,
 budget_from DECIMAL(12,2) NULL, budget_to DECIMAL(12,2) NULL, due_date DATE NULL,
 photos JSON NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'aberta', hidden TINYINT NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_market_posts(status,hidden,created_at),
 FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_proposals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, post_id BIGINT UNSIGNED NOT NULL,
 professional_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL, due_date DATE NOT NULL,
 message TEXT NOT NULL, experience TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'enviada',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_market_proposal(post_id,professional_id),
 FOREIGN KEY(post_id) REFERENCES market_posts(id) ON DELETE CASCADE,
 FOREIGN KEY(professional_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_works (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, post_id BIGINT UNSIGNED NOT NULL UNIQUE,
 proposal_id BIGINT UNSIGNED NOT NULL UNIQUE, customer_id BIGINT UNSIGNED NOT NULL, professional_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(120) NOT NULL, amount DECIMAL(12,2) NOT NULL, due_date DATE NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'andamento', customer_done TINYINT NOT NULL DEFAULT 0, professional_done TINYINT NOT NULL DEFAULT 0,
 pending_terms JSON NULL, provider_client_id BIGINT UNSIGNED NULL, provider_opportunity_id BIGINT UNSIGNED NULL,
 sale_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL, received_at DATETIME NULL,
 FOREIGN KEY(post_id) REFERENCES market_posts(id) ON DELETE CASCADE,
 FOREIGN KEY(proposal_id) REFERENCES market_proposals(id) ON DELETE CASCADE,
 FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(professional_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(provider_client_id) REFERENCES clients(id) ON DELETE SET NULL,
 FOREIGN KEY(provider_opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL,
 FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, work_id BIGINT UNSIGNED NOT NULL, sender_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, hidden TINYINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_market_chat(work_id,id), FOREIGN KEY(work_id) REFERENCES market_works(id) ON DELETE CASCADE,
 FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, work_id BIGINT UNSIGNED NOT NULL,
 author_id BIGINT UNSIGNED NOT NULL, target_id BIGINT UNSIGNED NOT NULL, stars TINYINT NOT NULL,
 comment VARCHAR(1000) NOT NULL DEFAULT '', hidden TINYINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uk_market_review(work_id,author_id),
 FOREIGN KEY(work_id) REFERENCES market_works(id) ON DELETE CASCADE,
 FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(target_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_blocks (
 user_id BIGINT UNSIGNED NOT NULL, target_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(user_id,target_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(target_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_suspensions (
 user_id BIGINT UNSIGNED PRIMARY KEY, reason VARCHAR(500) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reporter_id BIGINT UNSIGNED NOT NULL,
 target_type VARCHAR(20) NOT NULL, target_id BIGINT UNSIGNED NOT NULL, reason VARCHAR(1500) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'aberta', resolution VARCHAR(500) NULL, moderator_id BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at DATETIME NULL,
 FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(moderator_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_goals (
 user_id BIGINT UNSIGNED NOT NULL, month_key CHAR(7) NOT NULL, amount DECIMAL(12,2) NOT NULL,
 PRIMARY KEY(user_id,month_key), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS market_views (
 user_id BIGINT UNSIGNED NOT NULL, post_id BIGINT UNSIGNED NOT NULL, month_key CHAR(7) NOT NULL,
 PRIMARY KEY(user_id,post_id,month_key), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(post_id) REFERENCES market_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Expanded paid CRM capacities requested for this evolution. Pricing and billing identifiers unchanged.
UPDATE plans SET max_clients=NULL, max_quotes_per_month=NULL WHERE code IN ('pro','pro_max');
