import assert from 'node:assert/strict';
import { env } from '../config/env';
import { closePool, execute, queryOne, type RowDataPacket } from '../config/database';
import { clyQuota } from '../services/cly-quota.service';
import { aiService } from '../services/ai.service';
import { billingService, entitlementPlan } from '../services/billing.service';
const originalFetch = globalThis.fetch;
let checks = 0;
function check(value: unknown, message: string) { assert.ok(value,message);checks++;console.log('OK '+message); }
async function fail(action: () => Promise<unknown>, code: string) { await assert.rejects(action,{code});checks++; }
async function main() {
 if (env.isProduction || !/test/i.test(env.DB_NAME)) throw new Error('Use somente banco de teste.');
 const email = `cly.${Date.now()}@test.invalid`; const password='ClyTest@2026';
 const registered = await originalFetch(`${env.SMOKE_TEST_BASE_URL}/api/auth/register`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Teste Cly',email,password})});
 const body=await registered.json() as any;assert.equal(registered.status,201);const userId=body.data.user.id;
 const quota=await clyQuota.status(userId);check(quota.limit===3 && quota.consentRequired,'Free com 3 geracoes e consentimento obrigatorio');
 Object.assign(env,{ AI_PROVIDER:'openai',AI_API_KEY:'synthetic-test' });
 let providerCalls=0;
 globalThis.fetch=(async () => { providerCalls++; await new Promise(r=>setTimeout(r,40));return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'Sugestao para revisao'}]}]}),{status:200}); }) as typeof fetch;
 await fail(()=>aiService.generate(userId,'mensagem','Teste sem consentimento'),'AI_CONSENT_REQUIRED');
 check(providerCalls===0,'Sem consentimento nao chama provedor');
 await clyQuota.consent(userId,true);
 const parallel=await Promise.allSettled([1,2,3,4].map(()=>aiService.generate(userId,'mensagem','Mensagem de teste')));
 check(parallel.filter(v=>v.status==='fulfilled').length===1,'Uma geracao por vez sob concorrencia');
 check((await clyQuota.status(userId)).used===1,'Concorrencia nao duplica consumo');
 globalThis.fetch=(async ()=>new Response('unavailable',{status:503})) as typeof fetch;
 await fail(()=>aiService.generate(userId,'mensagem','Falha simulada'),'AI_UNAVAILABLE');
 check((await clyQuota.status(userId)).used===1 && !(await clyQuota.status(userId)).busy,'Falha nao consome cota e libera reserva');
 globalThis.fetch=(async ()=>new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'Teste'}]}]}),{status:200})) as typeof fetch;
 for (const hours of [2,4,8,8]) {
   while (!(await clyQuota.status(userId)).blocked) await aiService.generate(userId,'descricao','Descricao de teste');
   const row=await queryOne<RowDataPacket>('SELECT blocked_until, TIMESTAMPDIFF(MINUTE,UTC_TIMESTAMP(),blocked_until) AS minutes FROM cly_usage WHERE user_id=?',[userId]);
   check(row!.minutes>=hours*60-1 && row!.minutes<=hours*60,`Espera de ${hours} horas aplicada`);
   await fail(()=>aiService.generate(userId,'descricao','Nova tentativa'),'AI_LIMIT_REACHED');
   const after=await queryOne<RowDataPacket>('SELECT blocked_until FROM cly_usage WHERE user_id=?',[userId]);
   check(+new Date(after!.blocked_until)===+new Date(row!.blocked_until),'Tentativa bloqueada nao aumenta espera');
   await execute('UPDATE cly_usage SET blocked_until=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE user_id=?',[userId]);
 }
 await execute('UPDATE cly_usage SET last_exhausted_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 8 DAY) WHERE user_id=?',[userId]);
 check((await clyQuota.status(userId)).nextWaitHours===2,'Sete dias sem esgotar reiniciam progressao');
 await execute("UPDATE subscriptions SET plan_id=(SELECT id FROM plans WHERE code='pro') WHERE user_id=?",[userId]);
 await execute("UPDATE cly_usage SET month_key=DATE_FORMAT(UTC_TIMESTAMP(),'%Y-%m'),monthly_used=49 WHERE user_id=?",[userId]);
 await aiService.generate(userId,'proposta','Proposta de teste');
 const pro=await clyQuota.status(userId);check(pro.limit===50&&pro.blocked,'Pro bloqueia em 50 geracoes mensais');
 await fail(()=>aiService.generate(userId,'proposta','Proposta de teste'),'AI_LIMIT_REACHED');
 await execute("UPDATE subscriptions SET plan_id=(SELECT id FROM plans WHERE code='pro_max') WHERE user_id=?",[userId]);
 const plus=await clyQuota.status(userId);check(plus.limit===150&&plus.remaining===100,'Upgrade preserva uso mensal e amplia cota');
 await execute("UPDATE cly_usage SET month_key='2020-01' WHERE user_id=?",[userId]);
 check((await clyQuota.status(userId)).used===0,'Mes UTC novo renova a cota');
 await clyQuota.consent(userId,false);
 await fail(()=>aiService.generate(userId,'descricao','Teste'),'AI_CONSENT_REQUIRED');
 const expires=new Date(Date.now()+86400000).toISOString();
 const customer:any={ entitlements:{clyvo_pro:{product_identifier:'clyvo_pro_monthly',expires_date:expires}},subscriptions:{clyvo_pro_monthly:{store:'play_store',is_sandbox:false}} };
 check(entitlementPlan(customer,false).code==='pro','Assinatura de loja valida concede Pro');
 customer.subscriptions.clyvo_pro_monthly.is_sandbox=true;
 check(entitlementPlan(customer,false).code==='free','Compra sandbox nao libera producao');
 check(entitlementPlan(customer,true).code==='pro','Sandbox liberado apenas quando configurado');
 customer.subscriptions.clyvo_pro_monthly.refunded_at=new Date().toISOString();
 check(entitlementPlan(customer,true).code==='free','Reembolso remove beneficio');
 customer.subscriptions.clyvo_pro_monthly.refunded_at=null;customer.entitlements.clyvo_pro.expires_date='2020-01-01T00:00:00Z';
 check(entitlementPlan(customer,true).code==='free','Vencimento remove beneficio');
 check(entitlementPlan({},true).code==='free','Sem entitlement nao ha upgrade');
 Object.assign(env, { REVENUECAT_SECRET_KEY: 'synthetic-test' });
 globalThis.fetch=(async ()=>new Response('{}',{status:404})) as typeof fetch;
 await billingService.sync(userId,true);
 check((await queryOne<RowDataPacket>("SELECT p.code FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=?",[userId]))!.code==='free','Conta sem perfil RevenueCat continua Free');
 customer.entitlements.clyvo_pro.expires_date=expires;customer.subscriptions.clyvo_pro_monthly.is_sandbox=false;
 globalThis.fetch=(async ()=>new Response(JSON.stringify({subscriber:customer}),{status:200})) as typeof fetch;
 await billingService.sync(userId,true);
 check((await queryOne<RowDataPacket>("SELECT p.code FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=?",[userId]))!.code==='pro','Resposta verificada atualiza plano no banco');
 globalThis.fetch=(async ()=>new Response('error',{status:503})) as typeof fetch;
 await fail(()=>billingService.sync(userId,true),'BILLING_UNAVAILABLE');
 check((await queryOne<RowDataPacket>("SELECT p.code FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=?",[userId]))!.code==='pro','Falha do provedor nao apaga assinatura verificada');
 Object.assign(env,{REVENUECAT_SECRET_KEY:''});
 globalThis.fetch=originalFetch;
 await originalFetch(`${env.SMOKE_TEST_BASE_URL}/api/auth/delete-account`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});
 check(!(await queryOne<RowDataPacket>('SELECT * FROM cly_usage WHERE user_id=?',[userId])),'Exclusao remove consentimento e uso da Cly');
 console.log(`CLY: ${checks} verificacoes aprovadas; chamadas de IA simuladas.`);
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{globalThis.fetch=originalFetch;await closePool();});
